# Generated by Django 5.2.6 on 2025-11-20 06:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("kitchen_staff", "Kitchen Staff"),
                            ("kitchen_manager", "Kitchen Manager"),
                            ("cluster_manager", "Cluster Manager"),
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hybbconnect.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="KitchenLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(blank=True, max_length=50, null=True)),
                ("emp_name", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(default="UNKNOWN", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Reporting Issue", "Reporting Issue"),
                            ("Kot Process", "Kot Process"),
                            ("Behaviour Issue", "Behaviour Issue"),
                            ("Grooming", "Grooming"),
                            (
                                "Assigned Task Not Completed",
                                "Assigned Task Not Completed",
                            ),
                        ],
                        max_length=200,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "log_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Log Date"
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "kitchen_staff"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterManagerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_manager_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="cluster_managers", to="hybbconnect.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="order_photos/"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hybbconnect.location",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalarySlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("present_days", models.IntegerField(blank=True, null=True)),
                ("lop_days", models.IntegerField(blank=True, null=True)),
                (
                    "sac_off_ot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rating_incentive",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "km_mrd_incentive",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "arrears",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "referral_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mrd_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "km_mrd_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "photo_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "missing_item_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_slips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("bau_status", models.CharField(max_length=50)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "incentive",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ot_sacoff_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "referral_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dsat_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "wrong_order_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mrd_deduction_staff",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "earning_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "employee_code",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mobile_number",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "concern_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("concern", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Assigned", "Assigned"),
                            ("Reassigned", "Reassigned"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hybbconnect.location",
                    ),
                ),
            ],
        ),
    ]
