# Generated by Django 5.2.6 on 2025-11-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hybbconnect", "0001_initial"),
    ]

    operations = [
        # ❌ Removed AddField for 'reassigned_to' (it already exists in database)

        migrations.AlterField(
            model_name="ticket",
            name="concern_category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(default="No description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="employee_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hybbconnect.location",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
