# Generated by Django 5.2.6 on 2025-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0003_ticket_reassigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="staff_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="staff_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
