# Generated by Django 5.2.6 on 2025-12-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="closing_remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
