# Generated by Django 5.2.6 on 2025-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0006_ticket_closing_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cluster_closer_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="owner_closer_remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
