# Generated by Django 5.2.6 on 2025-12-05 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0007_ticket_cluster_closer_remarks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTimeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[("TO", "Time Off (TO)"), ("SAC_OFF", "SAC Off")],
                        max_length=20,
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("ot_date", models.DateField(blank=True, null=True)),
                ("sac_off_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
