# Generated by Django 5.2.6 on 2026-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0009_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
