# Generated by Django 5.2.6 on 2026-08-06 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybbconnect', '0010_attendance_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='UNKNOWN', max_length=50)),
                ('category', models.CharField(choices=[('Food Safety', 'Food Safety'), ('Food Quality', 'Food Quality'), ('Food Quantity', 'Food Quantity'), ('Code Red', 'Code Red'), ('Incomplete Order', 'Incomplete Order')], max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_date', models.DateField(default=django.utils.timezone.now, verbose_name='Feedback Date')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'kitchen_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
