# Generated by Django 5.2.6 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hybbconnect", "0011_qualityfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityfeedback",
            name="raised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raised_quality_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
