# Generated by Django 5.2.6 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hybbconnect", "0012_qualityfeedback_raised_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityfeedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("KOT Marking", "KOT Marking"),
                    ("Follow SOP", "Follow SOP"),
                    ("Quality Check", "Quality Check"),
                    ("Correct Portioning", "Correct Portioning"),
                    ("Order Verification before packing", "Order Verification before packing"),
                    ("Use Dossier", "Use Dossier"),
                    ("Follow dispatch checklist", "Follow dispatch checklist"),
                    ("Photo Adherence", "Photo Adherence"),
                    ("Productivity", "Productivity"),
                    ("Call Cust or Thank u notes", "Call Cust or Thank u notes"),
                ],
                max_length=100,
            ),
        ),
    ]
