# Generated by Codex on 2026-09-02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hybbconnect", "0013_alter_qualityfeedback_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStaffLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_date", models.DateField(default=django.utils.timezone.localdate)),
                ("first_login_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("login_count", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "kitchen_staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-login_date", "user__username"],
                "unique_together": {("user", "login_date")},
            },
        ),
    ]
