# Generated by Django 5.2.6 on 2026-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hybbconnect', '0015_notification_daily_update_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='qualityfeedback',
            name='category',
            field=models.CharField(choices=[('KOT Marking', 'KOT Marking'), ('Follow SOP', 'Follow SOP'), ('Quality Check', 'Quality Check'), ('Correct Portioning', 'Correct Portioning'), ('Order Verification before packing', 'Order Verification before packing'), ('Use Dossier', 'Use Dossier'), ('Follow dispatch checklist', 'Follow dispatch checklist'), ('Photo Adherence', 'Photo Adherence'), ('Productivity', 'Productivity'), ('Call Cust or Thank u notes', 'Call Cust or Thank u notes'), ('traning Coruse Not Completed - Salary Hold', 'traning Coruse Not Completed - Salary Hold')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'location'], name='user_role_location_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystafflogin',
            index=models.Index(fields=['login_date'], name='daily_login_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystafflogin',
            index=models.Index(fields=['user', 'login_date'], name='daily_login_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenlog',
            index=models.Index(fields=['location', '-created_at'], name='klog_location_created_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenlog',
            index=models.Index(fields=['log_date'], name='klog_date_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenlog',
            index=models.Index(fields=['staff', '-created_at'], name='klog_staff_created_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenlog',
            index=models.Index(fields=['is_acknowledged'], name='klog_ack_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notif_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderphoto',
            index=models.Index(fields=['location', '-uploaded_at'], name='photo_location_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='orderphoto',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='photo_user_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfeedback',
            index=models.Index(fields=['staff', '-created_at'], name='qfb_staff_created_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfeedback',
            index=models.Index(fields=['raised_by', '-created_at'], name='qfb_raised_created_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfeedback',
            index=models.Index(fields=['location', 'feedback_date'], name='qfb_location_date_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfeedback',
            index=models.Index(fields=['is_acknowledged'], name='qfb_ack_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimeupdate',
            index=models.Index(fields=['staff', '-updated_at'], name='stime_staff_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftimeupdate',
            index=models.Index(fields=['updated_by', '-updated_at'], name='stime_by_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['location', '-created_at'], name='ticket_location_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_owner', '-created_at'], name='ticket_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reassigned_to', '-created_at'], name='ticket_reassign_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['employee', '-created_at'], name='ticket_employee_created_idx'),
        ),
    ]
